### ISSUE TITLE
Allow to provide input file as a parameter

### ISSUE THREAD

**Issue by hmenager** [edamontology/edam2json-js#3]
EDAM input file could be a parameter of the edam2json command line tool.
An example of how to code this is here:
https://gitlab.pasteur.fr/hmenager/bioweb/-/blob/master/server/router.js
it uses the npm `commander` library, there might be newer and cooler libraries but this one used to work :wink:

**Comment by HagerDakroury** [comment]
hi @hmenager, are there any other initial commands to add other than `parse file`.

Also, do you think there should be different logic for executing from the command-line vs module export? eg. should this be placed together or differently

**Comment by hmenager** [comment]
Hello @HagerDakroury , here's a proposal for the command line syntax for the tool:

```
edam2json [jsontree, jsonld] [edam-owl-file]
commands: jsontree - generate a json representation of the EDAM hierarchy
                   jsonld - generate a json-ld formatted version of EDAM
edam-owl-file: the EDAM ontology file, as an OWL-rdf tool
```
by default, the output of the command line call should be printed to the standard output.

The package, used as a library, should enable to use not only these two options, but also more atomic functions, such as a function that would only parse the RDF, or another that would generate the "json tree" format from an object-oriented representation.
